INSERT INTO angularjs.course (id, creation_date, description, duration, is_top_rated, title) VALUES (1, '2019-10-02T12:24:00', '1Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam blanditiis cum eaque, fugiat hic libero minima nemo nulla, odit officia porro possimus, quo sed suscipit.', 15, false, 'Video Course 1');
INSERT INTO angularjs.course (id, creation_date, description, duration, is_top_rated, title) VALUES (2, '2019-11-25T13:24:00', '2Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam blanditiis cum eaque, fugiat hic libero minima nemo nulla, odit officia porro possimus, quo sed suscipit.', 20, false, 'Video Course 2');
INSERT INTO angularjs.course (id, creation_date, description, duration, is_top_rated, title) VALUES (3, '2019-10-22T14:24:00', '3Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam blanditiis cum eaque, fugiat hic libero minima nemo nulla, odit officia porro possimus, quo sed suscipit.', 25, true, 'Video Course 3');
INSERT INTO angularjs.course (id, creation_date, description, duration, is_top_rated, title) VALUES (4, '2019-11-01T15:24:00', '4Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam blanditiis cum eaque, fugiat hic libero minima nemo nulla, odit officia porro possimus, quo sed suscipit.', 30, false, 'Video Course 4');
INSERT INTO angularjs.course (id, creation_date, description, duration, is_top_rated, title) VALUES (5, '2019-10-23T15:24:00', '5Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam blanditiis cum eaque, fugiat hic libero minima nemo nulla, odit officia porro possimus, quo sed suscipit.', 35, false, 'Video Course 5');
INSERT INTO angularjs.course (id, creation_date, description, duration, is_top_rated, title) VALUES (6, '2019-10-23T15:24:00', '6Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam blanditiis cum eaque, fugiat hic libero minima nemo nulla, odit officia porro possimus, quo sed suscipit.', 125, false, 'Video Course 6');
INSERT INTO angularjs.course (id, creation_date, description, duration, is_top_rated, title) VALUES (7, '2019-10-23T15:24:00', '7Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam blanditiis cum eaque, fugiat hic libero minima nemo nulla, odit officia porro possimus, quo sed suscipit.', 60, false, 'Video Course 7');

INSERT INTO angularjs.user (id, email, first_name, last_name, login, password) VALUES (1, 'pup@gmail.com', 'Pup', 'Pupkov', 'adminLogin', '1111');
INSERT INTO angularjs.user (id, email, first_name, last_name, login, password) VALUES (2, 'user@gmail.com', 'Kop', 'Kopkov', 'userLogin', '1111');
